# Generated by Django 2.2.7 on 2019-11-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sslcommerzinformation',
            options={'verbose_name': 'SSLCommerz Informations', 'verbose_name_plural': 'SSLCommerz Informations'},
        ),
    ]
