# Generated by Django 2.2.7 on 2019-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0002_auto_20191124_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sslcommerzcredential',
            old_name='cancel_url',
            new_name='live_cancel_url',
        ),
        migrations.RenameField(
            model_name='sslcommerzcredential',
            old_name='fail_url',
            new_name='live_fail_url',
        ),
        migrations.RenameField(
            model_name='sslcommerzcredential',
            old_name='ipn_url',
            new_name='live_ipn_url',
        ),
        migrations.RenameField(
            model_name='sslcommerzcredential',
            old_name='success_url',
            new_name='live_success_url',
        ),
        migrations.AddField(
            model_name='sslcommerzcredential',
            name='sandbox_cancel_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sslcommerzcredential',
            name='sandbox_fail_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sslcommerzcredential',
            name='sandbox_ipn_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sslcommerzcredential',
            name='sandbox_success_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
