# Generated by Django 2.2.7 on 2019-11-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0003_auto_20191126_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sslcommerzcredential',
            options={'verbose_name': 'SSLCommerz', 'verbose_name_plural': 'SSLCommerz'},
        ),
    ]
