# Generated by Django 2.2.7 on 2019-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='baner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
