# Generated by Django 2.2.7 on 2019-11-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_baner_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='baner_title',
            new_name='banner_title',
        ),
    ]
