# Generated by Django 2.2.7 on 2019-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsitesettings',
            name='site_contact_name',
        ),
        migrations.RemoveField(
            model_name='mainsitesettings',
            name='site_contact_no',
        ),
        migrations.RemoveField(
            model_name='mainsitesettings',
            name='site_name',
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='og_description',
            field=models.CharField(default='The High End Fashion Retailer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='og_title',
            field=models.CharField(default='ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_cancel',
            field=models.CharField(default='Order Cancellation | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_cart',
            field=models.CharField(default='Shopping Bag | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_checkout',
            field=models.CharField(default='The High End Fashion Retailer | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_edit_profile',
            field=models.CharField(default='Update Profile | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_error',
            field=models.CharField(default='Order Error | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_payment',
            field=models.CharField(default='Payment Confirmation | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_profile',
            field=models.CharField(default='Profile | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_search_result',
            field=models.CharField(default='Search result | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_sign_in',
            field=models.CharField(default='Sign In | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_sign_up',
            field=models.CharField(default='Sign Up | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_success',
            field=models.CharField(default='Order Confirmation | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='page_title_update_password',
            field=models.CharField(default='Forgot password | ILLIYEEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='title',
            field=models.CharField(default='The High End Fashion Retailer | ILLIYEEN', max_length=100, null=True),
        ),
    ]
