# Generated by Django 2.2.7 on 2019-11-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('site_settings', '0002_auto_20191126_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCredSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_url', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('dev_username', models.CharField(max_length=100, null=True)),
                ('dev_password', models.CharField(max_length=100, null=True)),
                ('dev_application_id', models.CharField(max_length=100, null=True)),
                ('dev_message_id', models.CharField(max_length=100, null=True)),
                ('dev_authorization', models.CharField(max_length=100, null=True)),
                ('dev_sms_from', models.CharField(max_length=100, null=True)),
                ('live_url', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('live_username', models.CharField(max_length=100, null=True)),
                ('live_password', models.CharField(max_length=100, null=True)),
                ('live_application_id', models.CharField(max_length=100, null=True)),
                ('live_message_id', models.CharField(max_length=100, null=True)),
                ('live_authorization', models.CharField(max_length=100, null=True)),
                ('live_sms_from', models.CharField(max_length=100, null=True)),
                ('active_payment', models.CharField(choices=[('dev', 'DEV'), ('live', 'Live')], max_length=10)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
