# Generated by Django 2.2.7 on 2019-11-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_smscredsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscredsettings',
            old_name='active_payment',
            new_name='active_sms',
        ),
        migrations.AlterField(
            model_name='smscredsettings',
            name='dev_url',
            field=models.URLField(blank=True, help_text='SMS DEV URL', null=True),
        ),
    ]
