# Generated by Django 2.2.7 on 2019-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20191126_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicredentialsettings',
            options={'verbose_name': 'API Credential', 'verbose_name_plural': 'All API Credential'},
        ),
        migrations.AlterModelOptions(
            name='mainsitesettings',
            options={'verbose_name': 'Site Info', 'verbose_name_plural': 'All Site Info'},
        ),
        migrations.AlterModelOptions(
            name='smscredsettings',
            options={'verbose_name': 'SMS Credential', 'verbose_name_plural': 'All SMS Credential'},
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook URL', null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter URL', null=True),
        ),
        migrations.AddField(
            model_name='mainsitesettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='YouTube Channel URL', null=True),
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
