# Generated by Django 2.2.7 on 2019-11-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_auto_20191127_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicredentialsettings',
            name='gtag',
        ),
        migrations.AddField(
            model_name='apicredentialsettings',
            name='active_api',
            field=models.CharField(choices=[('dev', 'DEV'), ('live', 'Live')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apicredentialsettings',
            name='dev_report_url',
            field=models.URLField(blank=True, help_text='API DEV REPORT URL', null=True),
        ),
        migrations.AlterField(
            model_name='apicredentialsettings',
            name='dev_url',
            field=models.URLField(blank=True, help_text='API DEV URL', null=True),
        ),
    ]
