# Generated by Django 2.2.7 on 2019-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_auto_20191127_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsitesettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram URL', null=True),
        ),
    ]
