# Generated by Django 2.2.7 on 2019-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_mainsitesettings_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsitesettings',
            name='analytics',
            field=models.CharField(blank=True, help_text='Analytics', max_length=255, null=True),
        ),
    ]
