# Generated by Django 2.2.7 on 2019-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaycenters',
            name='center_address',
            field=models.TextField(help_text='Center Address'),
        ),
        migrations.AlterField(
            model_name='displaycenters',
            name='center_business_hours',
            field=models.TextField(help_text='Center Business Hours'),
        ),
        migrations.AlterField(
            model_name='displaycenters',
            name='center_contact_no',
            field=models.CharField(help_text='Center Contact No', max_length=100),
        ),
    ]
