# Generated by Django 2.2.7 on 2019-11-19 13:12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('display_centers', '0003_auto_20191119_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCentersDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('center_name', models.CharField(help_text='Center Name', max_length=100)),
                ('center_address', wagtail.core.fields.RichTextField(help_text='Center Address', null=True)),
                ('center_business_hours', wagtail.core.fields.RichTextField(help_text='Center Business Hours', null=True)),
                ('center_contact_no', models.CharField(help_text='Center Contact No', max_length=100)),
                ('center_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Display Center',
                'verbose_name_plural': 'Display Centers',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DisplayCentersListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='DisplayCenters',
        ),
    ]
