# Generated by Django 2.2.7 on 2019-11-27 08:02

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display_centers', '0004_auto_20191119_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaycentersdetailpage',
            name='center_address',
            field=wagtail.core.fields.RichTextField(help_text='Center Address', null=True, verbose_name='Center Address'),
        ),
        migrations.AlterField(
            model_name='displaycentersdetailpage',
            name='center_business_hours',
            field=wagtail.core.fields.RichTextField(help_text='Center Business Hours', null=True, verbose_name='Business Hours'),
        ),
        migrations.AlterField(
            model_name='displaycentersdetailpage',
            name='center_contact_no',
            field=models.CharField(help_text='Center Contact No', max_length=100, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='displaycentersdetailpage',
            name='center_name',
            field=models.CharField(help_text='Center Name', max_length=100, verbose_name='Center Name'),
        ),
    ]
