# Generated by Django 2.2.7 on 2019-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_centers', '0005_auto_20191127_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaycentersdetailpage',
            name='google_map_link',
            field=models.CharField(help_text='Google Map Link', max_length=100, null=True, verbose_name='Google Map Link'),
        ),
    ]
