# Generated by Django 2.2.7 on 2019-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_centers', '0006_displaycentersdetailpage_google_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaycentersdetailpage',
            name='center_contact_no',
            field=models.CharField(blank=True, help_text='Center Contact No', max_length=100, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='displaycentersdetailpage',
            name='google_map_link',
            field=models.CharField(blank=True, help_text='Google Map Link', max_length=100, null=True, verbose_name='Google Map Link'),
        ),
    ]
